version: '3.1'

services:
  db:
    image: postgres
    shm_size: '4gb'
    container_name: my_spot
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - my_spot
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  my_spot:
    name: my_spot

volumes:
  postgres:
    driver: local
