@url = http://localhost:5159/api
# @url = http://localhost:5000/api
@reservationId = 3d62e6af-d6f1-437a-af6a-4ba3c0a6dda7
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationId}}

###
POST {{url}}/reservations
Content-Type: application/json

{
    "ParkingSpotId": "{{parkingSpotId}}",
    "Date": "2023-05-10",
    "EmployeeName": "John Doe",
    "LicensePLate": "XYZ123"
}

###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "LicensePLate": "LOL1234"
}

###
DELETE {{url}}/reservations/{{reservationId}}