@url = http://localhost:5159/api
# @url = http://localhost:5000/api
@reservationId = 9e5e8797-52d2-4261-9fc0-374aeb80bd1d
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationId}}

###
POST {{url}}/reservations/vehicle
Content-Type: application/json

{
    "ParkingSpotId": "{{parkingSpotId}}",
    "Date": "2023-05-15",
    "EmployeeName": "John Doe",
    "LicensePLate": "XYZ123",
    "Capacity": 2
}

###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "LicensePLate": "LOL1234"
}

###
DELETE {{url}}/reservations/{{reservationId}}