@url = http://localhost:5159/api
@reservationId = 00000000-0000-0000-0000-000000000001
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/reservations

###
GET {{url}}/reservations/{{reservationId}}

###
POST {{url}}/reservations
Content-Type: application/json

{
    "ParkingSpotId": "{{parkingSpotId}}",
    "Date": "2023-05-07",
    "EmployeeName": "John Doe",
    "LicensePLate": "XYZ"
}

###
PUT {{url}}/reservations/{{reservationId}}
Content-Type: application/json

{
    "LicensePLate": "LOL"
}

###
DELETE {{url}}/reservations/{{reservationId}}